site_name: Discord-Bash Docs
site_description: 'Docs for Discord-Bash'
site_author: 'Cyber'
docs_dir: docs/
repo_url: 'https://github.com/CyberL1/Discord-Bash'
nav:
    - Home: index.md
    - Initial setup: initial-setup.md
    - Setup: setup.md
    - File structure: file-structure.md
    - Troubleshooting: troubleshooting.md
theme:
  name: 'material'
markdown_extensions:
  - pymdownx.tabbed
  - admonition
  - attr_list